package local_test

import (
	"context"
	"fmt"
	"io"
	"strings"
	"sync"
	"testing"

	"github.com/networkteam/sdd/internal/model"
	sdd "github.com/networkteam/sdd/pkg/application"
)

func TestCapturePublicationReturnsOriginalCommitAfterRestart(t *testing.T) {
	repo := newGitRepository(t)
	key := sdd.PublicationKey{Session: "session", Sequence: 4, Discriminator: "new-entry"}
	const entryID = "20260914-020000-s-tac-cap"
	batch := captureBatch(t, key, entryID, "Original summary.")
	batch.Attachments = []sdd.AttachmentMaterialization{{BlobID: "blob", SourceName: "evidence.md", LogicalPath: "2026/09/14-020000-s-tac-cap/evidence.md"}}
	if _, err := repo.graphStore().PublishEntry(t.Context(), key, batch, blobSources{"blob": "Immutable attachment."}); err != nil {
		t.Fatal(err)
	}
	if _, found, err := repo.graphStore().LookupEntryPublication(t.Context(), key, entryID); err != nil || found {
		t.Fatalf("uncommitted files counted as a publication: found=%v err=%v", found, err)
	}
	repo.finalize(batch)
	message := repo.git("log", "-1", "--format=%B")
	if !strings.Contains(message, "SDD-Mutation: "+key.String()) || strings.Contains(message, string(key.Session)) {
		t.Fatalf("commit must carry the opaque publication ID without a session handle: %q", message)
	}
	published := repo.git("rev-parse", "HEAD")
	repo.write("README", "Another session advanced the branch.\n")
	repo.git("add", "README")
	repo.git("commit", "-m", "test: advance unrelated state")
	store := repo.graphStore()
	lookup, found, err := store.LookupEntryPublication(t.Context(), key, entryID)
	if err != nil || !found || lookup.Revision != published {
		t.Fatalf("historical lookup = %+v, %v, %v", lookup, found, err)
	}
	batch.Changes[0].CanonicalBytes = []byte("Unusable regenerated bytes must not replace the publication.")
	retried, err := store.PublishEntry(t.Context(), key, batch, nil)
	if err != nil || retried.Revision != published || retried.Document.Frontmatter["summary"] != "Original summary." {
		t.Fatalf("publication retry = %+v, %v", retried, err)
	}
	if len(retried.Document.Attachments) != 1 || retried.Document.Attachments[0] != "evidence.md" {
		t.Fatalf("attachment inventory = %v", retried.Document.Attachments)
	}
	repo.finalize(batch)
	if count := repo.git("rev-list", "--count", "HEAD"); count != "3" {
		t.Fatalf("commit count = %s; retry added a commit", count)
	}
}

func TestCapturePublicationCountsOnlyAfterItsCommit(t *testing.T) {
	repo := newGitRepository(t)
	allowCommits := repo.failCommits()
	key := sdd.PublicationKey{Session: "session", Sequence: 5, Discriminator: "new-entry"}
	const entryID = "20260914-020100-s-tac-cap"
	batch := captureBatch(t, key, entryID, "First rendered summary.")
	store := repo.graphStore()
	if _, err := store.PublishEntry(t.Context(), key, batch, nil); err != nil {
		t.Fatal(err)
	}
	if err := repo.finalizer().Finalize(t.Context(), appliedCapture(batch)); err == nil {
		t.Fatal("failed Git commit reported completion")
	}
	if _, found, err := store.LookupEntryPublication(t.Context(), key, entryID); err != nil || found {
		t.Fatalf("worktree files were reported committed: found=%v err=%v", found, err)
	}
	allowCommits()
	batch = captureBatch(t, key, entryID, "Regenerated summary.")
	publication, err := store.PublishEntry(t.Context(), key, batch, nil)
	if err != nil || publication.Document.Frontmatter["summary"] != "First rendered summary." {
		t.Fatalf("publication retry = %+v, %v", publication, err)
	}
	repo.finalize(batch)
	lookup, found, err := store.LookupEntryPublication(t.Context(), key, entryID)
	if err != nil || !found || lookup.Revision != repo.git("rev-parse", "HEAD") || repo.git("rev-list", "--count", "HEAD") != "2" {
		t.Fatalf("retry did not finish exactly one Git publication: %+v, %v, %v", lookup, found, err)
	}
}

func TestConcurrentCaptureAttemptsCommitOnce(t *testing.T) {
	repo := newGitRepository(t)
	key := sdd.PublicationKey{Session: "session", Sequence: 6, Discriminator: "new-entry"}
	const entryID = "20260914-020200-s-tac-cap"
	batch := captureBatch(t, key, entryID, "Concurrent attempts share one publication.")
	const attempts = 6
	failures := make(chan error, attempts)
	var running sync.WaitGroup
	for range attempts {
		store := repo.graphStore()
		finalizer := repo.finalizer()
		running.Go(func() {
			if _, err := store.PublishEntry(t.Context(), key, batch, nil); err != nil {
				failures <- err
				return
			}
			failures <- finalizer.Finalize(t.Context(), appliedCapture(batch))
		})
	}
	running.Wait()
	for range attempts {
		if err := <-failures; err != nil {
			t.Fatalf("concurrent attempt: %v", err)
		}
	}
	if count := repo.git("rev-list", "--count", "HEAD"); count != "2" {
		t.Fatalf("concurrent attempts produced %s commits", count)
	}
	if lookup, found, err := repo.graphStore().LookupEntryPublication(t.Context(), key, entryID); err != nil || !found || lookup.Revision != repo.git("rev-parse", "HEAD") {
		t.Fatalf("publication lookup = %+v, %v, %v", lookup, found, err)
	}
}

func TestCapturePublicationMatchesTheWholeDiscriminator(t *testing.T) {
	repo := newGitRepository(t)
	key := sdd.PublicationKey{Session: "session", Sequence: 7, Discriminator: "new-entry"}
	const entryID = "20260914-020300-s-tac-cap"
	batch := captureBatch(t, key, entryID, "Publication identity includes the entire discriminator.")
	store := repo.graphStore()
	if _, err := store.PublishEntry(t.Context(), key, batch, nil); err != nil {
		t.Fatal(err)
	}
	repo.finalize(batch)
	key.Discriminator = "new"
	if _, found, err := store.LookupEntryPublication(t.Context(), key, entryID); err != nil || found {
		t.Fatalf("a discriminator prefix matched another publication: found=%v err=%v", found, err)
	}
}

func (r *gitRepository) finalize(batch sdd.MutationBatch) {
	r.t.Helper()
	if err := r.finalizer().Finalize(r.t.Context(), appliedCapture(batch)); err != nil {
		r.t.Fatal(err)
	}
}

func appliedCapture(batch sdd.MutationBatch) sdd.AppliedMutation {
	return sdd.AppliedMutation{Project: "example", BatchID: batch.ID, Batch: batch}
}

func captureBatch(t *testing.T, key sdd.PublicationKey, id, summary string) sdd.MutationBatch {
	t.Helper()
	filename, err := model.IDToRelPath(id)
	if err != nil {
		t.Fatal(err)
	}
	canonical := []byte("---\ntype: signal\nkind: gap\nlayer: tactical\nconfidence: high\nparticipants: [Christopher]\nsummary: " + summary + "\n---\n\nAn entry published through its recorded invocation.\n")
	document, err := sdd.ParseEntryDocument(filename, canonical)
	if err != nil {
		t.Fatal(err)
	}
	return sdd.MutationBatch{ID: key.String(), Message: "sdd: capture " + id, Changes: []sdd.DocumentChange{{LogicalPath: filename, CanonicalBytes: canonical, Document: &document}}}
}

type blobSources map[string]string

func (b blobSources) Open(_ context.Context, id string) (io.ReadCloser, error) {
	value, exists := b[id]
	if !exists {
		return nil, fmt.Errorf("blob %s is not staged", id)
	}
	return io.NopCloser(strings.NewReader(value)), nil
}
