package local_test

import (
	"context"
	"fmt"
	"io"
	"strings"
	"sync"
	"testing"

	"github.com/networkteam/sdd/internal/model"
	sdd "github.com/networkteam/sdd/pkg/application"
)

func TestCapturePublicationReturnsOriginalCommitAfterRestart(t *testing.T) {
	repo := newGitRepository(t)
	key := sdd.PublicationKey{Session: "session", Sequence: 4, Discriminator: "new-entry"}
	batch := captureBatch(t, key, "20260914-020000-s-tac-cap", "Original summary.")
	batch.Attachments = []sdd.AttachmentMaterialization{{BlobID: "blob", SourceName: "evidence.md", LogicalPath: "2026/09/14-020000-s-tac-cap/evidence.md"}}
	first, err := repo.graphStore().PublishEntry(t.Context(), key, batch, blobSources{"blob": "Immutable attachment."})
	if err != nil {
		t.Fatal(err)
	}
	repo.write("README", "Another session advanced the branch.\n")
	repo.git("add", "README")
	repo.git("commit", "-m", "test: advance unrelated state")
	store := repo.graphStore()
	lookup, found, err := store.LookupEntryPublication(t.Context(), key, "20260914-020000-s-tac-cap")
	if err != nil || !found || lookup.Revision != first.Revision {
		t.Fatalf("historical lookup = %+v, %v, %v", lookup, found, err)
	}
	batch.Changes[0].CanonicalBytes = []byte("Unusable regenerated bytes must not replace the publication.")
	retried, err := store.PublishEntry(t.Context(), key, batch, nil)
	if err != nil || retried.Revision != first.Revision || retried.Document.Frontmatter["summary"] != "Original summary." {
		t.Fatalf("publication retry = %+v, %v", retried, err)
	}
	if len(retried.Document.Attachments) != 1 || retried.Document.Attachments[0] != "evidence.md" {
		t.Fatalf("attachment inventory = %v", retried.Document.Attachments)
	}
	if count := repo.git("rev-list", "--count", "HEAD"); count != "3" {
		t.Fatalf("commit count = %s; retry added a commit", count)
	}
}

func TestCapturePublicationRequiresGitCommitAndRetriesExistingFiles(t *testing.T) {
	repo := newGitRepository(t)
	allowCommits := repo.failCommits()
	key := sdd.PublicationKey{Session: "session", Sequence: 5, Discriminator: "new-entry"}
	batch := captureBatch(t, key, "20260914-020100-s-tac-cap", "First rendered summary.")
	if _, err := repo.graphStore().PublishEntry(t.Context(), key, batch, nil); err == nil {
		t.Fatal("failed Git commit reported publication success")
	}
	if _, found, err := repo.graphStore().LookupEntryPublication(t.Context(), key, "20260914-020100-s-tac-cap"); err != nil || found {
		t.Fatalf("worktree files were reported committed: found=%v err=%v", found, err)
	}
	allowCommits()
	batch = captureBatch(t, key, "20260914-020100-s-tac-cap", "Regenerated summary.")
	publication, err := repo.graphStore().PublishEntry(t.Context(), key, batch, nil)
	if err != nil || publication.Document.Frontmatter["summary"] != "First rendered summary." {
		t.Fatalf("commit retry = %+v, %v", publication, err)
	}
	if publication.Revision != repo.git("rev-parse", "HEAD") || repo.git("rev-list", "--count", "HEAD") != "2" {
		t.Fatal("retry did not finish exactly one Git publication")
	}
}

func TestConcurrentCaptureAttemptsCommitOnce(t *testing.T) {
	repo := newGitRepository(t)
	key := sdd.PublicationKey{Session: "session", Sequence: 6, Discriminator: "new-entry"}
	batch := captureBatch(t, key, "20260914-020200-s-tac-cap", "Concurrent attempts share one publication.")
	const attempts = 6
	results := make(chan sdd.EntryPublication, attempts)
	errors := make(chan error, attempts)
	var running sync.WaitGroup
	for range attempts {
		store := repo.graphStore()
		running.Go(func() {
			publication, err := store.PublishEntry(t.Context(), key, batch, nil)
			results <- publication
			errors <- err
		})
	}
	running.Wait()
	wantRevision := repo.git("rev-parse", "HEAD")
	for range attempts {
		publication, err := <-results, <-errors
		if err != nil || publication.Revision != wantRevision {
			t.Fatalf("concurrent attempt = %+v, %v", publication, err)
		}
	}
	if count := repo.git("rev-list", "--count", "HEAD"); count != "2" {
		t.Fatalf("concurrent attempts produced %s commits", count)
	}
}

func TestCapturePublicationMatchesTheWholeDiscriminator(t *testing.T) {
	repo := newGitRepository(t)
	key := sdd.PublicationKey{Session: "session", Sequence: 7, Discriminator: "new-entry"}
	batch := captureBatch(t, key, "20260914-020300-s-tac-cap", "Publication identity includes the entire discriminator.")
	store := repo.graphStore()
	if _, err := store.PublishEntry(t.Context(), key, batch, nil); err != nil {
		t.Fatal(err)
	}
	key.Discriminator = "new"
	if _, found, err := store.LookupEntryPublication(t.Context(), key, "20260914-020300-s-tac-cap"); err != nil || found {
		t.Fatalf("a discriminator prefix matched another publication: found=%v err=%v", found, err)
	}
}

func captureBatch(t *testing.T, key sdd.PublicationKey, id, summary string) sdd.MutationBatch {
	t.Helper()
	filename, err := model.IDToRelPath(id)
	if err != nil {
		t.Fatal(err)
	}
	canonical := []byte("---\ntype: signal\nkind: gap\nlayer: tactical\nconfidence: high\nparticipants: [Christopher]\nsummary: " + summary + "\n---\n\nAn entry published through its recorded invocation.\n")
	document, err := sdd.ParseEntryDocument(filename, canonical)
	if err != nil {
		t.Fatal(err)
	}
	return sdd.MutationBatch{ID: key.String(), Message: "sdd: capture " + id, Changes: []sdd.DocumentChange{{LogicalPath: filename, CanonicalBytes: canonical, Document: &document}}}
}

type blobSources map[string]string

func (b blobSources) Open(_ context.Context, id string) (io.ReadCloser, error) {
	value, exists := b[id]
	if !exists {
		return nil, fmt.Errorf("blob %s is not staged", id)
	}
	return io.NopCloser(strings.NewReader(value)), nil
}
