package local_test

import (
	"bytes"
	"errors"
	"strings"
	"testing"

	sdd "github.com/networkteam/sdd/pkg/application"
)

// A retried summary correction finds its own commit by key and leaves a later
// correction from another session in place: S1 corrects to X and loses its
// reply, S2 corrects to Y, S1 retries and gets X back without touching Y.
func TestDocumentPublicationRetryFindsItsOwnCommitAndKeepsLaterWrites(t *testing.T) {
	repo := newGitRepository(t)
	store := repo.graphStore()
	const entryID = "20260923-010000-s-tac-sum"
	capture := sdd.PublicationKey{Session: "s1", Sequence: 2, Discriminator: "newEntry"}
	batch := captureBatch(t, capture, entryID, "Generated.")
	if _, err := store.PublishEntry(t.Context(), capture, batch, nil); err != nil {
		t.Fatal(err)
	}
	repo.finalize(batch)
	logicalPath := batch.Changes[0].LogicalPath

	first := sdd.PublicationKey{Session: "s1", Sequence: 4, Discriminator: "replaceSummary:" + entryID}
	current, err := store.ReadDocument(t.Context(), logicalPath)
	if err != nil || current.Absent {
		t.Fatalf("ReadDocument = %+v, %v", current, err)
	}
	x := bytes.Replace(current.Content, []byte("summary: Generated."), []byte("summary: X."), 1)
	if _, err := store.PublishDocument(t.Context(), first, sdd.DocumentMutation{LogicalPath: logicalPath, Content: x, ExpectedBlob: sdd.GitBlobID(current.Content), Message: "s1 corrects"}); err != nil {
		t.Fatal(err)
	}
	repo.finalizeDocument(first, logicalPath, x)
	firstCommit := repo.git("rev-parse", "HEAD")

	second := sdd.PublicationKey{Session: "s2", Sequence: 3, Discriminator: "replaceSummary:" + entryID}
	y := bytes.Replace(x, []byte("summary: X."), []byte("summary: Y."), 1)
	if _, err := store.PublishDocument(t.Context(), second, sdd.DocumentMutation{LogicalPath: logicalPath, Content: y, ExpectedBlob: sdd.GitBlobID(x), Message: "s2 corrects"}); err != nil {
		t.Fatal(err)
	}
	repo.finalizeDocument(second, logicalPath, y)

	retried, err := store.PublishDocument(t.Context(), first, sdd.DocumentMutation{LogicalPath: logicalPath, Content: []byte("regenerated bytes must not be written"), ExpectedBlob: sdd.GitBlobID(current.Content), Message: "s1 retries"})
	if err != nil || retried.Revision != firstCommit || !bytes.Equal(retried.Content, x) {
		t.Fatalf("retry of the first correction = %+v, %v; want its own commit %s carrying X", retried, err, firstCommit)
	}
	now, err := store.ReadDocument(t.Context(), logicalPath)
	if err != nil || !bytes.Equal(now.Content, y) {
		t.Fatalf("the later correction was overwritten: %s", now.Content)
	}
	repo.finalizeDocument(first, logicalPath, x)
	if count := repo.git("rev-list", "--count", "HEAD"); count != "4" {
		t.Fatalf("commit count = %s; the retry added a commit", count)
	}

	// A fresh correction from a stale read is a conflict, not a silent overwrite.
	stale := sdd.PublicationKey{Session: "s3", Sequence: 2, Discriminator: "replaceSummary:" + entryID}
	_, err = store.PublishDocument(t.Context(), stale, sdd.DocumentMutation{LogicalPath: logicalPath, Content: x, ExpectedBlob: sdd.GitBlobID(current.Content), Message: "stale"})
	var appErr *sdd.ApplicationError
	if !errors.As(err, &appErr) || appErr.Code != sdd.ErrorGraphConflict {
		t.Fatalf("stale correction = %v, want %s", err, sdd.ErrorGraphConflict)
	}
}

// A marker removal counts only after its commit: removed files with a failed
// commit are completed by the retry, and removing an absent marker publishes
// nothing while never touching another marker.
func TestDocumentRemovalCountsOnlyAfterItsCommit(t *testing.T) {
	repo := newGitRepository(t)
	store := repo.graphStore()
	const marker = "wip/20260923-010000-christopher.md"
	const other = "wip/20260923-010100-someone-else.md"
	content := []byte("---\nentry: 20260923-010000-s-tac-sum\nparticipant: Christopher\nexclusive: true\n---\n\nWork.\n")
	for path, key := range map[string]sdd.PublicationKey{marker: {Session: "s1", Sequence: 2, Discriminator: "wipStart:a"}, other: {Session: "s9", Sequence: 2, Discriminator: "wipStart:b"}} {
		if _, err := store.PublishDocument(t.Context(), key, sdd.DocumentMutation{LogicalPath: path, Content: content, Message: "start"}); err != nil {
			t.Fatal(err)
		}
		repo.finalizeDocument(key, path, content)
	}
	allowCommits := repo.failCommits()
	remove := sdd.PublicationKey{Session: "s1", Sequence: 6, Discriminator: "wipDone:a"}
	removed, err := store.PublishDocument(t.Context(), remove, sdd.DocumentMutation{LogicalPath: marker, Message: "done"})
	if err != nil || !removed.Absent || removed.Revision == "" {
		t.Fatalf("removal = %+v, %v; want absent with a revision to commit", removed, err)
	}
	if err := repo.finalizer().Finalize(t.Context(), removalMutation(remove, marker)); err == nil {
		t.Fatal("the commit was expected to fail")
	}
	if _, found, err := store.LookupDocumentPublication(t.Context(), remove, marker); err != nil || found {
		t.Fatalf("an uncommitted removal counted as a publication: found=%v err=%v", found, err)
	}
	allowCommits()
	again, err := store.PublishDocument(t.Context(), remove, sdd.DocumentMutation{LogicalPath: marker, Message: "done"})
	if err != nil || !again.Absent || again.Revision == "" {
		t.Fatalf("retried removal = %+v, %v; the branch still carries the file, so there is a removal to commit", again, err)
	}
	repo.finalizeDocument(remove, marker, nil)
	looked, found, err := store.LookupDocumentPublication(t.Context(), remove, marker)
	if err != nil || !found || !looked.Absent {
		t.Fatalf("committed removal lookup = %+v, %v, %v", looked, found, err)
	}
	if listed := repo.git("ls-tree", "--name-only", "HEAD", "--", ".sdd/graph/wip/"); !strings.Contains(listed, other) || strings.Contains(listed, marker) {
		t.Fatalf("branch after removal lists %q", listed)
	}

	absent := sdd.PublicationKey{Session: "s1", Sequence: 8, Discriminator: "wipRemove:a"}
	none, err := store.PublishDocument(t.Context(), absent, sdd.DocumentMutation{LogicalPath: marker, Message: "remove again"})
	if err != nil || !none.Absent || none.Revision != "" {
		t.Fatalf("removing an absent marker = %+v, %v; want absent with nothing to commit", none, err)
	}
	if current, err := store.ReadDocument(t.Context(), other); err != nil || current.Absent {
		t.Fatalf("another marker was touched: %+v, %v", current, err)
	}
}

func removalMutation(key sdd.PublicationKey, logicalPath string) sdd.AppliedMutation {
	batch := sdd.MutationBatch{ID: key.String(), Message: "sdd: wip done", Changes: []sdd.DocumentChange{{LogicalPath: logicalPath, Delete: true}}}
	return sdd.AppliedMutation{Project: "example", BatchID: batch.ID, Batch: batch}
}

// finalizeDocument commits one document publication the way the application
// does after PublishDocument; nil content is a removal.
func (r *gitRepository) finalizeDocument(key sdd.PublicationKey, logicalPath string, content []byte) {
	r.t.Helper()
	batch := sdd.MutationBatch{ID: key.String(), Message: "sdd: document " + logicalPath, Changes: []sdd.DocumentChange{{LogicalPath: logicalPath, CanonicalBytes: content, Delete: content == nil}}}
	if err := r.finalizer().Finalize(r.t.Context(), sdd.AppliedMutation{Project: "example", BatchID: batch.ID, Batch: batch}); err != nil {
		r.t.Fatal(err)
	}
}
